name: laravel-ci

on: [push, pull_request]

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: mvc_mesa
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysql, dom, fileinfo
          coverage: none

      - name: Instalar dependencias
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Configurar .env para CI
        run: |
          cp .env.example .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=mvc_mesa/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=/' .env
          sed -i 's|APP_URL=.*|APP_URL=http://localhost|' .env

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Verificar conexión MySQL
        run: |
          sudo apt-get install -y mysql-client
          until mysql -h127.0.0.1 -uroot -e "SHOW DATABASES;"; do
            echo "Esperando a MySQL..."
            sleep 5
          done

      - name: Migrar base de datos
        run: php artisan migrate:fresh --seed --force
