name: Laravel CI

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, intl, sqlite

      - name: Instalar dependencias
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copiar archivo .env
        run: cp .env.example .env

      - name: Generar APP_KEY
        run: php artisan key:generate

      - name: Preparar base de datos SQLite
        run: |
          touch database/database.sqlite
          php artisan migrate --force --database=sqlite

      - name: Ejecutar pruebas
        run: php artisan test
